version: '3'

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

services:
  postgres:
    image: postgres
    volumes:
       - postgres-data:/var/lib/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgres
    networks:
      - dev
    ports:
      - "5432:5432"
  server:
    ports:
      - "8000:8000"
    build:
      context: .
    volumes:
      - .:/opt/project:delegated
      - ../conf:/opt/conf
    networks:
      - dev
    depends_on:
      - postgres
      - redis
    command: python manage.py runserver 0.0.0.0:8000
  celery:
    profiles:
      - celery
    build:
      context: .
    volumes:
      - .:/opt/project:delegated
      - ../conf:/opt/conf
    networks:
      - dev
    environment:
      C_FORCE_ROOT: 1
    command: celery worker -A application -E
  redis:
    image: redis:3.2
    networks:
      - dev
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
